/**
 * P2P Protocol Constants
 * Based on BOLT 1: Base Protocol specifications
 */

export const P2P_CONSTANTS = {
  // Protocol version
  PROTOCOL_VERSION: 0,

  // Network magic bytes (Bitcoin mainnet)
  NETWORK_MAGIC: Buffer.from([0xf9, 0xbe, 0xb4, 0xd9]),

  // Message length limits
  MAX_MESSAGE_LENGTH: 65535, // 2^16 - 1
  MIN_MESSAGE_LENGTH: 2, // type (2 bytes)

  // Connection limits
  DEFAULT_MAX_CONNECTIONS: 10,
  DEFAULT_CONNECTION_TIMEOUT: 30000, // 30 seconds
  DEFAULT_HEARTBEAT_INTERVAL: 30000, // 30 seconds
  DEFAULT_RECONNECT_ATTEMPTS: 3,
  DEFAULT_RECONNECT_DELAY: 5000, // 5 seconds

  // Lightning P2P ports
  DEFAULT_LIGHTNING_PORT: 9735,

  // Noise Protocol constants
  NOISE_PROTOCOL_NAME: 'Noise_XK_25519_ChaChaPoly_SHA256',
  NOISE_HANDSHAKE_PATTERN: 'XK',

  // Message type ranges
  CONTROL_MESSAGE_MIN: 16,
  CONTROL_MESSAGE_MAX: 31,
  CHANNEL_MESSAGE_MIN: 32,
  CHANNEL_MESSAGE_MAX: 127,
  HTLC_MESSAGE_MIN: 128,
  HTLC_MESSAGE_MAX: 255,
  ANNOUNCEMENT_MESSAGE_MIN: 256,
  ANNOUNCEMENT_MESSAGE_MAX: 511,

  // Error codes
  ERROR_UNKNOWN_PEER: 1,
  ERROR_INVALID_MESSAGE: 2,
  ERROR_HANDSHAKE_FAILED: 3,
  ERROR_ENCRYPTION_FAILED: 4,
  ERROR_CONNECTION_LOST: 5,
  ERROR_PROTOCOL_VIOLATION: 6,
  ERROR_RATE_LIMITED: 7,

  // Feature flags (BOLT 9)
  FEATURE_OPTION_DATA_LOSS_PROTECT: 1 << 0,
  FEATURE_OPTION_INITIAL_ROUTING_SYNC: 1 << 3,
  FEATURE_OPTION_UPFRONT_SHUTDOWN_SCRIPT: 1 << 4,
  FEATURE_OPTION_GOSSIP_QUERIES: 1 << 6,
  FEATURE_OPTION_STATIC_REMOTE_KEY: 1 << 12,
  FEATURE_OPTION_ANCHOR_OUTPUTS: 1 << 20,
  FEATURE_OPTION_ANCHORS_ZERO_FEE_HTLC_TX: 1 << 22,

  // TLV types (BOLT 1)
  TLV_TYPE_PADDING: 1,
  TLV_TYPE_PUBKEY: 2,
  TLV_TYPE_SHORT_CHANNEL_ID: 3,
  TLV_TYPE_AMOUNT: 4,
  TLV_TYPE_CLTV_EXPIRY: 5,
  TLV_TYPE_HTLC_SIGNATURE: 6,
  TLV_TYPE_FEE_PROPORTIONAL_BASIS_POINTS: 7,
  TLV_TYPE_FEE_BASE_MSAT: 8,
  TLV_TYPE_CHANNEL_FLAGS: 9,
  TLV_TYPE_SHUTDOWN_SCRIPT_PUBKEY: 10,
  TLV_TYPE_CHAIN_HASH: 11,
  TLV_TYPE_CONFIRMATION_HEIGHT: 12,
  TLV_TYPE_TEMPORARY_CHANNEL_ID: 13,
  TLV_TYPE_COMMON_BLOCK_HEIGHT: 14,
  TLV_TYPE_NEXT_PER_COMMITMENT_POINT: 15,
  TLV_TYPE_NEXT_FUNDING: 16,
  TLV_TYPE_UPFRONT_SHUTDOWN_SCRIPT: 17,
  TLV_TYPE_REMOTE_FUNDING_PUBKEY: 18,
  TLV_TYPE_FUNDING_ACK: 19,
  TLV_TYPE_CLOSING_SIGNATURE: 20,
} as const

// Known Lightning seed nodes for initial peer discovery
export const SEED_NODES = [
  { host: '03fce1651050c93bd5b2dc0801091347fc1a4c4aea1ff4ba5d4c558a6a0b6c0e9c1', port: 9735 },
  { host: '02c1c68ba3a1e26e2edbf8840b0c6e4d3e1c1c68ba3a1e26e2edbf8840b0c6e4d3e', port: 9735 },
  { host: '036b53093b3d8c8e1e3c8c7b8c7b8c7b8c7b8c7b8c7b8c7b8c7b8c7b8c7b8c7b8c', port: 9735 },
] as const

// Default P2P configuration
export const DEFAULT_P2P_CONFIG = {
  maxConnections: P2P_CONSTANTS.DEFAULT_MAX_CONNECTIONS,
  connectionTimeout: P2P_CONSTANTS.DEFAULT_CONNECTION_TIMEOUT,
  heartbeatInterval: P2P_CONSTANTS.DEFAULT_HEARTBEAT_INTERVAL,
  reconnectAttempts: P2P_CONSTANTS.DEFAULT_RECONNECT_ATTEMPTS,
  reconnectDelay: P2P_CONSTANTS.DEFAULT_RECONNECT_DELAY,
  listenPort: P2P_CONSTANTS.DEFAULT_LIGHTNING_PORT,
  enableTLS: true,
} as const
